config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :home
  devise_for :users
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  belongs_to :sub_category
  has_many :models
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :brand
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :model
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  has_many :brands
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def devise_mapping
    Devise.mappings[:user]
  end

  def resource_name
    devise_mapping.name
  end

  def resource_class
    devise_mapping.to
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GuitaRigTube</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/navigation' %>
<% if notice %>
  <p class="alert alert-success" role="alert"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger" role="alert"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "GuitaRigTube", root_path, :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-list"></i> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left form-inline" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-user"></i> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to(raw('<i class="glyphicon glyphicon-edit"></i> Edit Profile'), edit_user_registration_path) %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to(raw('<i class="glyphicon glyphicon-log-out"></i> Log Out'), destroy_user_session_path, :method => :delete) %>
                </li>
              </ul>
          </li>
        <% else %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-log-in"></i> <span class="caret"></span></a>
              <ul class="dropdown-menu sign-in">
                <%= form_for(@user, url: session_path(@user), :html => {:class => "sign-in-form"}, ) do |f| %>
                  <div class="form-group">
                    <%= f.email_field :email, autofocus: true, :class => "form-control", :placeholder => "Email" %>
                  </div>
                  <div class="form-group">
                    <%= f.password_field :password, autocomplete: "off", :class => "form-control", :placeholder => "Password" %>
                  </div>
                  <% if devise_mapping.rememberable? -%>
                    <div class="form-group">
                      <%= f.check_box :remember_me %>
                      <%= f.label :remember_me %>
                    </div>
                  <% end -%>
                  <div class="form-group">
                    <%= f.submit "Log in", class: "btn btn-primary" %>
                  </div>
                  <%= render "users/shared/links" %>
                <% end %>
                <li role="separator" class="divider"></li>
                <div class="social-media-sign-in">
                  <li>
                    or sign in with:
                  </li>
                  <li>
                    <ul class="list-inline text-center social-media-sign">
                      <li><a href="#" class="social-media-btn"><%= image_tag("social-media/facebook.png", :class => "img-circle") %></a></li>
                      <li><a href="#" class="social-media-btn"><%= image_tag("social-media/twitter.png", :class => "img-circle") %></a></li>
                      <li><a href="#" class="social-media-btn"><%= image_tag("social-media/googleplus.png", :class => "img-circle") %></a></li>
                    </ul>
                  </li>
                </div>
              </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/shared/_links.html.erb
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>